# Generated by Django 3.2.4 on 2021-06-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isodatabank", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiliaExcelFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.BinaryField()),
                ("dataset_id", models.CharField(max_length=50)),
            ],
        ),
    ]
