# Generated by Django 3.2.4 on 2021-06-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("isodatabank", "0002_tiliaexcelfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationinformation",
            name="original_paper_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
